environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '10'
      SPELLCHECKER_PREFER_HUNSPELL: true
    - nodejs_version: '8'
    - nodejs_version: '6'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm --msvs_version=2015 install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
